name: mowie
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  photo_view: ^0.9.2
  flutter_typeahead: ^1.8.6






  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
     - images/


  fonts:
     - family: SourceSansPro
       fonts:
         - asset: fonts/SourceSansPro-Bold.ttf

     - family: NotoSans
       fonts:
          - asset: fonts/NotoSans-Bold.ttf
          - asset: fonts/NotoSans-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
